# Generated by Django 5.0.3 on 2024-03-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_amount', models.BigIntegerField()),
                ('extracted_amount', models.BigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.filemanager')),
            ],
        ),
    ]
