# Generated by Django 5.0.3 on 2024-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
